### ISSUE TITLE
UPN QR still active?

### ISSUE THREAD

**Issue by gredler** [greymag/dart_upn_qr#1]
The UPN QR website (https://upn-qr.si/) seems to have been taken down. Is this standard still active?

The website was still available in February, but seemed to have some sort of end-of-life message?

https://web.archive.org/web/20240227025346/https://upn-qr.si/

**Comment by greymag** [comment]
Hello. 

Yes, this site was shut down due to the discontinuation of the free QR code verification service ([link](https://www.zbs-giz.si/banke-in-hranilnice-s-1-1-2023-ukinjajo-storitev-brezplacnega-preverjanja-pravilnosti-qr-kode-na-obrazcu-upnqr/)).

But the standard is still relevant and used by the majority of companies.

You can find information and manuals on the ZBS website.

https://www.zbs-giz.si/placilni-promet/

**Comment by gredler** [comment]
Ah, got it. Thanks!
